config/routes.rb
FakeBook::Application.routes.draw do
  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :index, :show] do
    resources :posts, only: [:create, :destroy, :new]
    resources :friendships, only: [:create, :destroy]
  end

  resource :feed, only: :show

  root to: "feeds#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :user1_id, :user2_id
  validates :user1_id, :user2_id, presence: true
  validates :user1_id, uniqueness: {scope: :user2_id}

  belongs_to(
    :user1,
    class_name: "User",
    foreign_key: :user1_id,
    primary_key: :id
  )
  belongs_to(
    :user2,
    class_name: "User",
    foreign_key: :user2_id,
    primary_key: :id
  )

  def create_two_friendships
    complement = Friendship.new(
      user1_id: self.user2_id,
      user2_id: self.user1_id
    )

    transaction do
      self.save
      complement.save
    end
  end

  def destroy_two_friendships
    complement = Friendship.find_by_user1_id_and_user2_id(
      self.user2_id,
      self.user1_id
    )

    transaction do
      complement.destroy
      self.destroy
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :link, :message, :user_id
  validates :message, :user_id, presence: true

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  def self.sort_posts(posts)
    oldest_first = posts.sort_by do |post|
      post.created_at
    end

    newest_first = oldest_first.reverse
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :session, :username, :confirmation

  validates :password, length: {minimum: 6}
  validates :session, uniqueness: true
  validates :username, uniqueness: true

  after_initialize :require_session

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :user_id,
    primary_key: :id
  )
  has_many(
    :friendships,
    class_name: "Friendship",
    foreign_key: :user1_id,
    primary_key: :id
  )
  has_many(
    :friends,
    through: :friendships,
    source: :user2
  )

  def confirmation=(confirmation)
    @confirmation = confirmation
  end

  def password_confirmed?
    password == @confirmation
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.password == password ? user : nil
  end

  def self.generate_session
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session!
    self.session = User.generate_session
    self.save!
  end

  def require_session
    self.session ||= User.generate_session
  end

  def self.alphabetize_users
    User.all.sort_by do |user|
      user.name.downcase
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :require_user!

  def show
    unsorted_friends_posts = grab_friends_posts(current_user)
    @friends_posts = Post.sort_posts(unsorted_friends_posts)
    render :show
  end

  private
  def grab_friends_posts(user)
    posts = []
    friends = user.friends.includes(:posts)

    friends.each do |friend|
      friend.posts.each do |post|
        posts << post
      end
    end

    posts
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :require_user!

  def create
    friendship = Friendship.new(
      user1_id: current_user.id,
      user2_id: params[:user_id]
    )

    friendship.create_two_friendships
    redirect_to user_url(id: params[:user_id])
  end

  def destroy
    friendship = Friendship.find(params[:id])
    friendship.destroy_two_friendships
    redirect_to user_url(id: params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_user!

  def new
    @user = User.find(params[:user_id])
    @posts = @user.posts
    if @user == current_user
      render :new
    else
      flash[:errors] = ["You can only post to your own profile"]
      redirect_to user_url(@user)
    end
  end

  def create
    post = Post.new(params[:post])
    user = User.find(params[:user_id])

    unless user == current_user
      redirect_to user_url(user)
      return
    end

    post.user_id = params[:user_id]
    if post.save
      redirect_to user_url(user)
    else
      flash[:errors] = post.errors.full_messages
      redirect_to new_user_post_url(user_id: user.id)
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy if post.user == current_user
    redirect_to user_url(id: params[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_user!, only: [:create, :new]
  before_filter :require_user!, only: [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      flash[:errors] = ["Credentials were wrong"]
      redirect_to new_session_url
    else
      self.current_user = user
      redirect_to root_url
    end
  end

  def destroy
    logout!
    redirect_to root_url
  end

  def new
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user!, only: [:new, :create]
  before_filter :require_user!, only: [:index, :show]

  def new
    render :new
  end

  def create
    user = User.new(params[:user])

    unless user.password_confirmed?
      flash[:errors] = ["Passwords don't match"]
      redirect_to new_user_url
      return
    end

    if user.save
      self.current_user = user
      redirect_to root_url
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def index
    @friends = current_user.friends
    @users = User.alphabetize_users
    render :index
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.sort_posts(@user.posts)
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session(session[:token])
  end

  def current_user=(user)
    @current_user = user
    session[:token] = user.session
  end

  def logout!
    current_user.reset_session!
    session[:token] = nil
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_user!
    self.logout! unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/show.html.erb
<% @is_current_user_profile = false %>
<% @user_id = -1 %>

<h1>News Feed (posts from friends)</h1>

<ul class="posts">
  <% @friends_posts.each do |post| %>
    <% @post = post %>
    <% @post_link = post.link %>
    <% user = post.user %>

    <li class="post">
      <a href="<%= user_url(user) %>" class="name"><%= user.name %></a>
      <%= render partial: "./posts/post_list_item_content" %>
    </li>
  <% end %>
</ul>

app/views/layouts/_nav_bar.html.erb
<% signed_in = !!current_user %>

<div id="nav-bar">
  <ul id="nav-list">
    <li><span id="logo">fakebook</span></li>
    <li>
      <% if signed_in %>
        <a href="<%= user_url(current_user) %>">Your Profile</a>
      <% else %>
        <a href="<%= new_session_url %>">Your Profile</a>
      <% end %>
    </li>
    <li>
      <% if signed_in %>
        <a href="<%= feed_url %>">Your Feed</a>
      <% else %>
        <a href="<%= new_session_url %>">Your Feed</a>
      <% end %>
    </li>
    <li>
      <% if signed_in %>
        <a href="<%= users_url %>">User Directory</a>
      <% else %>
        <a href="<%= new_session_url %>">User Directory</a>
      <% end %>
    </li>
    <li>
      <% if signed_in %>
        <span>Signed in as: <%= current_user.name %>
          <%= button_to "Sign Out", session_url, method: :delete %></span>
      <% else %>
        <span>Not signed in
          <%= button_to "Sign In", new_session_url, method: :get %></span>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>fakebook *by cesario uy*</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:errors] %>
<ul class="errors">
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<div class="wrapper">
  <%= render partial: "./layouts/nav_bar" %>
</div>

<div class="content">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_post_list_item_content.html.erb
<p><%= @post.message %></p>
<% if @post_link %>
  <a href="<%= @post_link %>" target="_blank"><%= @post_link %></a>
<% end %>

<% if @is_current_user_profile %>
  <%= button_to "Delete Post",
    user_post_url(user_id: @user_id, id: @post.id),
    method: :delete %>
<% end %>

app/views/posts/_posts_list.html.erb
<% @is_current_user_profile = (@user == current_user) %>
<% @user_id = @user.id %>

<ul class="posts">
  <% @posts.each do |post| %>
    <% @post = post %>
    <% @post_link = post.link %>

    <li class="post">
      <%= render partial: "./posts/post_list_item_content" %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1><%= @user.name %></h1>

<form action="<%= user_posts_url(@user) %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >

  <label>Message:<br>
    <textarea name="post[message]"></textarea>
  </label>

  <br><br>

  <label>Optional link (prefix with "http://..."):<br>
    <input type="text" name="post[link]">
  </label>

  <br><br>

  <input type="submit" value="Post message">
</form>

<%= button_to "Cancel", user_url(@user), method: :get %>

<%= render partial: "posts_list" %>

app/views/users/index.html.erb
<% current_user_id = current_user.id %>

<h1>All Users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <% user_id = user.id%>

    <li class="user">
      <a href="<%= user_url(user) %>" class="name"><%= user.name %></a>
      <% if user_id == current_user_id %>
        <span>(you)</span>
      <% elsif @friends.include?(user) %>
        <span>(friend)</span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<form action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
  >

  <label>Name:
    <input name="user[name]" type="text">
  </label>

  <br>

  <label>Username:
    <input name="user[username]" type="text">
  </label>

  <br>

  <label>Password:
    <input name="user[password]" type="password">
  </label>

  <br>

  <label>Confirm password:
    <input name="user[confirmation]" type="password">
  </label>

  <br>

  <input type="submit" value="Create account">
</form>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% user_id, current_user_id = @user.id, current_user.id %>

<% if user_id == current_user_id %>
  <%= button_to "Add Post",
    new_user_post_url(user_id: user_id),
    method: :get %>

<% elsif current_user.friends.include?(@user) %>
  <% friendship = Friendship.find_by_user1_id_and_user2_id(
    current_user_id, user_id) %>
  <%= button_to "Unfriend",
    user_friendship_url(user_id: user_id, id: friendship.id),
    method: :delete %>

<% else %>
  <%= button_to "Add as friend",
    user_friendships_url(user_id: user_id),
    method: :post %>
<% end %>

<%= render partial: "./posts/posts_list" %>